### ISSUE TITLE
HTML Editor jump line, errase two frist letters when add dot

### ISSUE THREAD

**Issue by Provoo** [tagspaces/tagspaces-android-lite#3]
I have been trying to reach or note this bug a lot of times, is very annoying when I'm using the app to write my notes, almost all the app is all right but I have this inconvenience, also the screen keyboard doesn't let you see what are you writing when you reach to the bottom.

I'm a professional developer if you want I can help you fix the bugs

**Comment by uggrock** [comment]
this should not be the case anymore in our last version: https://github.com/tagspaces/tagspaces/releases/download/v3.7.8/tagspaces-beta-3.7.8.apk
